### ISSUE TITLE
[Question] Is it possible to do JOINT training with NER(labeling) & intent( classification)?

### ISSUE THREAD

**Issue by ahtso** [BrikerMan/Kashgari#200]
As title, I want to use Kashgari package to implement the issue, which is the intent classification. By adding the NER task to support the intent classifier to perform better.
Is that possible using Kashgari to do joint training? If could, what should I do, is there any advice? Thank you very much.
By the way, if u don't mind, may I type Chinese?

**Comment by BrikerMan** [comment]
Yes, you can use Chinese, and you can run join-task by adding a special token.

Let's assume you have a sample like this.

```python
sentence = ['token0', 'token1', 'token2']
label = 'movie'
tag = ['O', 'O', 'B-Name']
```

## The easy way

Since kashgari will pad at the end of the sentence, you can add a special token at the began of sentence like this and add the label to the tags.

```python
sentence = ['#CLASSIFICATION#', 'token0', 'token1', 'token2']
tag = ['movie', 'O', 'O', 'B-Name']
```

Then you can train a model for classification and labeling.

## The better way

You can define a multi-output model like [this](https://kashgari.bmio.net/advance-use/multi-output-model/).
