### ISSUE TITLE
[Question] The input sequence length for Bert-BiLSTM-CRF and Save the best model

### ISSUE THREAD

**Issue by SharpKoi** [BrikerMan/Kashgari#436]
## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Ubuntu 18.04.3 LTS(On google colab)
- Python Version: Python 3.6.9
- requirements.txt: 

```txt
numpy>=1.18.1
gensim>=3.8.1
pandas==1.1.4
tensorflow==2.3.0
kashgari>=2.0.0
```

## Question
1. I have tried BiLSTM_CRF_Model with bert embedding layer to fit my dataset for NER task.
However, the length of each sequence in training data and testing data is almost longer than 2000. And it seems that the model I tried only accepts sequences with length at most 512.
Is there anyway to modify it? or I should look for other embedding models?
To solve it I currently split data into subdata with size 511, but I still worry about those tokens on the split line.
2. Is there anyway to save the model in the best epoch? Or can I pass ```tf.keras.callbacks.ModelCheckpoint``` into your fit  
callbacks argument?
I have reviewed the related issues but those answers seem to be in old version.

**Comment by BrikerMan** [comment]
1. the first issue is related to BERT Embedding, the max sequence that can be processed by BERT is 512. [discussion](https://www.reddit.com/r/MachineLearning/comments/genjvb/d_why_is_the_maximum_input_sequence_length_of/)
You need to look for other embedding models.

2. You can pass your `tf.keras.callbacks` or you own callback. But tf.keras.callbacks.ModelCheckpoint might not work since we need to save Kashgari's config. The best solution will be customizing a callback and call `model.save` when you need it.

**Comment by SharpKoi** [comment]
Thanks for getting back to me! I'll try your solution to customize my own callback and post here if I have any problems. Thanks anyway.
