### ISSUE TITLE
[Feature request] Support custom features

### ISSUE THREAD

**Issue by bratao** [BrikerMan/Kashgari#90]
Hello everyone. First of all, I'm very impressed by the quality of this project. It is truly production ready!

To one task I need a tagger, I need to work with Custom/hand crafted features.

For example, our OCR engine output a rich formation, like italic, bold e font size.

Would be possible to also utilize some handcrafted features for training/tagging in Kashgari?

**Comment by BrikerMan** [comment]
Hi, tell me more about your data. Maybe we could help you out.

**Comment by bratao** [comment]
You´re awesome @BrikerMan . 

I will Take this opportunity to explain my problem to you 😍 😍 

My task is to extract/segment information from a semi structured text. But not only the text is important some "external features" are also important.

For example, imagine that I want to segment this text about GitHub projects in Category, Project name, URl and description.

![image](https://user-images.githubusercontent.com/1090152/58190397-d14c0380-7c92-11e9-91e2-c1b9dd62737a.png)

I utilize an BIO scheme to tag each html token as a category. 

Where
token=NLP start_of_p=True bold=True center=True B-Category
token=Projects start_of_p=False bold=True center=True I-Category
token=Project start_of_p=True bold=True center=False B-Project-name
token=Name start_of_p=False bold=True center=False I-Project-name
token=: start_of_p=False bold=False center=False I-Project-name

The final result is something like:

![image](https://user-images.githubusercontent.com/1090152/58190447-eaed4b00-7c92-11e9-9279-f331324c828b.png)

Pay attention that some features are important such as: Text formatting (italic, bold, centered), position in text and more...

Right now I use a simple CRF, using all features. The results are OK right now. But I´m interested in verifying how Neural Networks would behave in this kind of task.

My main challenges in using neural networks/kashgari for this problem are two:
- The text sequences can be VERY long. I´m [Here](https://machinelearningmastery.com/handle-long-sequences-long-short-term-memory-recurrent-neural-networks/) there are some ideas such as Truncated Backpropagation Through Time.  For Kashgari I will try to split the input sequence into multiple fixed-length sub-sequences.
- The model need to consider those features.

Any insight would be very important for me. Thank you so much for your time and attention!!

**Comment by BrikerMan** [comment]
I have added a solution for cases like this in the new tf.keras version. Check this out, [handle numeric features](https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/deal_with_numeric_features.html). As for the first problem, I will try to fix that a little bit later.

**Comment by bratao** [comment]
Wow. I'm super ultra excited. Thank you so much @BrikerMan 
Tomorrow I will test and followup here with the results! 👏 👏 👏 👏

**Comment by alexwwang** [comment]
> I have added a solution for cases like this in the new tf.keras version. Check this out, [handle numeric features](https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/deal_with_numeric_features.html). As for the first problem, I will try to fix that a little bit later.

Genius! When I wrote two-heads embedding layers, I considered this problem so I left a general implementation easy to expand for more than two inputs while embedding. Glad to see that you have done the whole work!

Another two questions I've not made clearly is that: 
1) Does it matter if we embed those numeric features input into different places of a given deep model, rather than concatenate them together before pass into the model?
2) Does it matter if different numeric features share the same scale value in their representation vectors? e.g. both a noun and a B-of-Project-Name are represented as 1 in their feature vectors respectively?

I've not read any articles discussing these topics yet. Do you have any ideas?

**Comment by BrikerMan** [comment]
> > I have added a solution for cases like this in the new tf.keras version. Check this out, [handle numeric features](https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/deal_with_numeric_features.html). As for the first problem, I will try to fix that a little bit later.
> 
> Genius! When I wrote two-heads embedding layers, I considered this problem so I left a general implementation easy to expand for more than two inputs while embedding. Glad to see that you have done the whole work!
> 
> Another two questions I've not made clearly are these:
> 
> 1. Does it matter if we embed those numeric features input into different places of a given deep model, rather than concatenate them together before pass into the model?
> 2. Does it matter if different numeric features share the same scale value in their representation vectors? e.g. both a noun and a B-of-Project-Name are represented as 1 in their feature vectors respectively?
> 
> I've not read any articles discussing these topics yet. Do you have any ideas?

1. We could embed numeric features into different places of our model, like input feature 1 after LSTM-layer1 and feature-2 after LSTM-2. But, is this case, it will be a very specific model, and hard to modulize. If concatenate them together, then we could change the classification/labeling model any time we wanted.
2. It actually doesn't matter, since each feature has it's own embedding layer. But, if embedding layers share their weights, then we need to use different represent.

**Comment by alexwwang** [comment]
> > > I have added a solution for cases like this in the new tf.keras version. Check this out, [handle numeric features](https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/deal_with_numeric_features.html). As for the first problem, I will try to fix that a little bit later.
> > 
> > 
> > Genius! When I wrote two-heads embedding layers, I considered this problem so I left a general implementation easy to expand for more than two inputs while embedding. Glad to see that you have done the whole work!
> > Another two questions I've not made clearly are these:
> > 
> > 1. Does it matter if we embed those numeric features input into different places of a given deep model, rather than concatenate them together before pass into the model?
> > 2. Does it matter if different numeric features share the same scale value in their representation vectors? e.g. both a noun and a B-of-Project-Name are represented as 1 in their feature vectors respectively?
> > 
> > I've not read any articles discussing these topics yet. Do you have any ideas?
> 
>     1. We could embed numeric features into different places of our model, like input feature 1 after LSTM-layer1 and feature-2 after LSTM-2. But, is this case, it will be a very specific model, and hard to modulize. If concatenate them together, then we could change the classification/labeling model any time we wanted.
> 
>     2. It actually doesn't matter, since each feature has it's own embedding layer. But, if embedding layers share their weights, then we need to use different represent.

You remind me with 2nd point, yes, it's ok because they have different weights in each embedding layer. And it seems available to generalize this idea of embedding to apply to numeric features, say, even if we have some numeric features, such as the length of each sentence/passage, the number of certain words/emojis each sentence contains, all of them could be embedded first before pass into the model.

Back to the 1st question, I understand what you mean and it's actually the easy way to build this generalized model structure as we abstract three parts from the whole model. Though lack of proof, I think these two kinds of structure are mathematically equivalent because the weights of model would make this happen during training. So I think my doubt has been cleared and we shall move on. 😄

**Comment by BrikerMan** [comment]
@alexwwang Here is one more thing, at first, I tried to support multi-input for each Embedding Layers. But, now, it seems the smart way is to support multi-input using a stacked-embedding. I might remove multi-input handle capability from Embedding layers, which makes Embedding layer's code very messy. Any idea?

**Comment by alexwwang** [comment]
I agree with you. I've read your doc on stacked-embedding, and I think it's
a more beautiful and flexible way to assemble different kinds of embeddings
with models to support multi-inputs. I like your new design, concise and
delightful. 👍

**Comment by bratao** [comment]
It is working wonderfully. I will close this one. Just for organizing, I will open a Feature request for the Long Sequence support. Thank you!!

**Comment by armadillowithsunglasses** [comment]
Hi, 

first of all , this is a great resource ! 

I had one question (as I am new to Deep learning it may be trivial) 
I wanted to use this feature for my data which is of the format [text , numerical feature 1, numerical feature 2] however unlike the example where the features have distinct values (bold/ italic etc.) I have continuous values eg. 0.001, 0.003, 0.102 etc.

the NumericFeaturesEmbedding requires me to provide a feature count [2 for the example above] , how do I modify this for my data ? 

thank you so much :)

**Comment by BrikerMan** [comment]
@armadillowithsunglasses This might be tricky. Since we use an `Embedding Layer` in the numerical  Embedding, it only accepts int values. You might try to simply multiply your values with 1000, then you get an int numerical features. And the count is 1000.

**Comment by alexwwang** [comment]
What? Only accepts int value? How come?
Couldn’t we improve this?

**Comment by BrikerMan** [comment]
> What? Only accepts int value? How come? Couldn’t we improve this?

As I mention at https://github.com/BrikerMan/Kashgari/issues/158#issuecomment-511742666. We need to concatenating outputs of text-embedding and feature embeddings, so, since text-emebdding output is a 3D tensor, I used an embedding layer to convert numeric features to 3D tensor, which makes it impossible to receive float inputs.

**Comment by BrikerMan** [comment]
Maybe we should add A toy layer to convert features like this 

```python
sample_feature = [0.1, 0.21, 0.22]
```

To 

```python
sample_feature = [[0.1], [0.21], [0.22]]
```

Then we could concatenate to text embedding output.

**Comment by alexwwang** [comment]
Well, I will refer to documents related first and then figure out if
there’s any possibility to improve.

**Comment by alexwwang** [comment]
That seem to be what I did before. And in this way, multiple dimensions
numerical features would be accepted to concatenate.
